version: '3'
services:
  db:
    image: postgres:latest
    container_name: servicoAlunos_postgres
    restart: always
    environment:
      POSTGRES_USER: alunos
      POSTGRES_PASSWORD: Maxs251289#
      POSTGRES_DB: db_alunos
    ports:
      - "5481:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
